### ISSUE TITLE
are these old software's still maintained?

### ISSUE THREAD

**Issue by SoftMngBHD** [microsoft/LIS3.5#7]
just wondering, have these very old repos still looked at or used, or are they a thing of the past?

**Comment by chvalean** [comment]
LIS drivers are nowadays baked into the Linux kernel, so you don't have to install this separately, only on older releases/kernels that have none or old LIS drivers.
Have a look here: https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-linux-and-freebsd-virtual-machines-for-hyper-v-on-windows

**Comment by SoftMngBHD** [comment]
good to know, thanks for answering!
